Namespace Enums.Villians
    Public Enum COH_CC_Villians_Groups
        FifththColumn '5thColumn
        AntiMatter
        Arachnoids
        Arachnos
        Arachnos_60s
        AxisAmerica
        BanishedPantheon
        BattleMaiden
        Batzul
        BlackSwan
        Bobcat
        Cabal
        CapauDiableDemons
        Carnival
        Chimera
        CircleOfThorns
        CircleOfThornsEvent
        Clockwork
        ConsortiumGuards
        Contaminated
        Coralax
        Council
        Crazed
        Crey
        DevouringEarth
        DevouringEarthPraetorian
        Diabolique
        Dockworkers
        Dominatrix
        Fey
        FirBolg
        Freakshow
        FreedomCorps
        FreedomPhalanx
        GenericHeroes
        GenericVillains
        Ghosts
        GhoulsClean
        GhoulsDirty
        GoldBrickers
        Hellions
        Hydra
        Igneous
        Infected
        Infernal
        KnivesOfArtemis
        LegacyChain
        Loyalists
        Luddites
        Malaise
        Malta
        Marauder
        MastermindPets
        Midnight_Squad
        Miscellaneous
        Mooks
        MotherMayhem
        Nemesis
        NemesisAutomatons
        Neuron
        Nictus
        Nightstar
        NPC_Civilians
        NPC_Pets
        Objects
        Outcasts
        ParagonHeroes
        ParagonPolice
        ParagonProtectors
        Peacebringers
        Pets
        PracticeRobots
        PraetorianClockworkAntiMatter
        PraetorianClockworkLoyalist
        PraetorianClockworkMetronome
        PraetorianClockworkNeuron
        PraetorianClockworkResistance
        PraetorianIDF
        PraetorianPolice
        PraetorianResistance
        PraetorianTEST
        PraetorianWarWorks
        Prisoners
        PsychicClockwork
        RedCaps
        RedCapsEvent
        Rikti
        RogueArachnos
        RogueIslandPolice
        RogueIslesVillains
        RogueParagonPolice
        RogueRobots
        Romans
        Romans_Good
        Rularuu
        Scrapyarders
        Security_Guards
        ShadowHunter
        Shivan
        Siege
        SirensCallPhantom
        Skulls
        SkyRaiders
        SlagGolems
        Snakes
        SoulScavengers
        SpectralPirates
        SpetsnazCommandos
        Syndicate
        TEST_GROUP
        TheDestroyers
        TheFamily
        TheLost
        Thugs
        Trolls
        Tsoo
        Tuatha
        Tyrant
        UnderDwellers
        Unique
        Vahzilok
        Vanguard_Shield
        Vanguard_Sword
        Vindicators
        Wailers
        Warriors
        Werewolves
        WISDOM
        Wyvern
        Zig
    End Enum
    Public Enum COH_CC_Villians_Classes
        Minion_Grunt
        Minion_Small
        Minion_Small_Agressive
        Minion_Turret
        Minion_Fire
        Lt_Grunt
        Lt_Sniper
        Lt_Turret
        Boss_Grunt
        Boss_Elite
        Boss_Turret
        Boss_Monster
        Boss_Archvillain
        Minion_Swarm
        Boss_Mito
        Boss_Hamidon
        Boss_RularuuFM
        Boss_Rularuu
        Minion_Practice
        Lt_Practice
        Boss_Practice
        Minion_Pets
        Boss_Signature_Pets
        Minion_Henchman
        Lt_Henchman
        Boss_Henchman
        Minion_OilSlickTarget
        Minion_Monument
        Boss_Guard
        Lt_LongRangeDrone
        Minion_UnkillableNPC
        Boss_Monster_Flying
        Boss_Archvillain_Flying
        Boss_Shield
        Boss_HeavyPet
        Boss_PraetorianArchvillain
        Boss_PraetorianElite
        Boss_PraetorianGrunt
        Lt_PraetorianGrunt
        Minion_PraetorianGrunt
        Minion_PraetorianSmall
        Boss_RularuuCoP
    End Enum
End Namespace