Namespace CodeManagement.Enums.Databases.SQL
	Public Enum SQL_ENUM_Procedures
		ASQL_SEARCH_FOR_ACCOUNT = 0
		ASQL_FIND_OR_CREATE_ACCOUNT
		ASQL_UPDATE_ACCOUNT
		ASQL_ADD_MICRO_TRANSACTION
		ASQL_ADD_GAME_TRANSACTION
		ASQL_ADD_MULTI_GAME_TRANSACTION
		ASQL_SAVE_GAME_TRANSACTION
		ASQL_REVERT_GAME_TRANSACTION
		ASQL_READ_UNSAVED_GAME_TRANSACTIONS
		ASQL_STORED_PROCEDURE_MAX
	End Enum
End Namespace